version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geolocations-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/geolocations
    depends_on:
      - db
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload 

  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: geolocations-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  pgadmin:
    container_name: geolocations-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "6060:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin_data:
