"""Change string to 45

Revision ID: 162260f7817d
Revises: 906fdc25ae03
Create Date: 2024-07-23 13:09:35.909517

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "162260f7817d"
down_revision: Union[str, None] = "906fdc25ae03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "standardised_asset_type",
        existing_type=sa.String(length=50),  # previous length
        type_=sa.String(length=45),  # new length
        existing_nullable=True,  # or False if the column is not nullable
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "standardised_asset_type",
        existing_type=sa.String(length=45),  # new length
        type_=sa.String(length=50),  # previous length
        existing_nullable=True,  # or False if the column is not nullable
    )
    # ### end Alembic commands ###
