"""modify linestring to geometry

Revision ID: 215769b40600
Revises: dad71379d93a
Create Date: 2024-07-22 13:25:27.314734

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "215769b40600"
down_revision: Union[str, None] = "dad71379d93a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pipes")
    op.create_table(
        "pipes",
        sa.Column("pipe_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                srid=4326, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.Column("material", sa.String(length=200), nullable=True),
        sa.Column("pipe_key", sa.String(length=100), nullable=True),
        sa.Column("created_date", sa.Date(), nullable=True),
        sa.Column("diameter_mm", sa.Float(), nullable=True),
        sa.Column("pipe_type", sa.String(length=200), nullable=True),
        sa.Column("pipe_subtype", sa.String(length=45), nullable=True),
        sa.Column("standardised_material", sa.String(length=45), nullable=True),
        sa.Column("dma_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("pipe_id"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_assets_geom_indexed", table_name="assets", postgresql_using="gist"
    )
    op.drop_index("idx_assets_geom", table_name="assets", postgresql_using="gist")
    op.drop_table("assets")
    op.drop_index("idx_pipes_geom", table_name="pipes", postgresql_using="gist")
    op.drop_table("pipes")
    op.drop_index("idx_dmas_geom", table_name="dmas", postgresql_using="gist")
    op.drop_table("dmas")
    op.drop_index("idx_city_geo_location", table_name="city", postgresql_using="gist")
    op.drop_table("city")
    # ### end Alembic commands ###
