"""Change string to 65

Revision ID: 8ea185940dbd
Revises: 162260f7817d
Create Date: 2024-07-23 13:13:52.722673

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ea185940dbd"
down_revision: Union[str, None] = "162260f7817d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "standardised_asset_type",
        existing_type=sa.String(length=45),  # previous length
        type_=sa.String(length=65),  # new length
        existing_nullable=True,  # or False if the column is not nullable
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        "standardised_asset_type",
        existing_type=sa.String(length=65),  # new length
        type_=sa.String(length=45),  # previous length
        existing_nullable=True,  # or False if the column is not nullable
    )
    # ### end Alembic commands ###
