"""Change string to 50

Revision ID: 906fdc25ae03
Revises: 215769b40600
Create Date: 2024-07-23 12:59:33.422433

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "906fdc25ae03"
down_revision: Union[str, None] = "215769b40600"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        sa.Column("standardised_asset_type", sa.String(length=50), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assets",
        sa.Column("standardised_asset_type", sa.String(length=45), nullable=True),
    )
    # ### end Alembic commands ###
