"""Create pipes and assets

Revision ID: dad71379d93a
Revises: 03fd816667e3
Create Date: 2024-04-11 06:54:00.937901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'dad71379d93a'
down_revision: Union[str, None] = '03fd816667e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_key', sa.String(length=100), nullable=True),
    sa.Column('asset_type', sa.String(length=200), nullable=True),
    sa.Column('asset_subtype', sa.String(length=45), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('diameter_mm', sa.Float(), nullable=True),
    sa.Column('standardised_asset_type', sa.String(length=45), nullable=True),
    sa.Column('dma_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('geom_indexed', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dma_id'], ['dmas.dma_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_key', 'asset_subtype', name='uooipqspoiqsioqsp')
    )
    op.create_table('pipes',
    sa.Column('pipe_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('material', sa.String(length=200), nullable=True),
    sa.Column('pipe_key', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('diameter_mm', sa.Float(), nullable=True),
    sa.Column('pipe_type', sa.String(length=200), nullable=True),
    sa.Column('pipe_subtype', sa.String(length=45), nullable=True),
    sa.Column('standardised_material', sa.String(length=45), nullable=True),
    sa.Column('dma_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('geom_indexed', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dma_id'], ['dmas.dma_id'], ),
    sa.PrimaryKeyConstraint('pipe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipes')
    op.drop_table('assets')
    # ### end Alembic commands ###
