"""Add dmas2

Revision ID: e46d016f64ef
Revises: e06356d61589
Create Date: 2024-03-26 12:34:40.950014

"""
from typing import Sequence, Union
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46d016f64ef'
down_revision: Union[str, None] = 'e06356d61589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmas',
    sa.Column('dma_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dma_key', sa.String(length=200), nullable=True),
    sa.Column('dma_name', sa.String(length=100), nullable=True),
    sa.Column('dma_long', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('show_in_report', sa.Integer(), nullable=True),
    sa.Column('geom_str', sa.String(length=1000), nullable=True),
    sa.Column('max_bug_coverage', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('dma_id'),
    sa.UniqueConstraint('dma_key', name='uix_1'),
    sa.UniqueConstraint('geom_str', name='uix_2')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dmas_geom', table_name='dmas', postgresql_using='gist')
    op.drop_table('dmas')
    op.drop_index('idx_city_geo_location', table_name='city', postgresql_using='gist')
    op.drop_table('city')
    # ### end Alembic commands ###
